/*******************************************************************************
 * FILE        : Mcu_Cfg.h
 * DESCRIPTION : AUTOSAR Mcu Driver — Compile-Time Configuration
 *               Pre-compile configuration constants and feature switches.
 *               In production: generated by DaVinci Configurator / ISOLAR.
 *               Here: written manually for NXP S32K144 @ 112MHz.
 *
 * SPEC        : AUTOSAR_CP_SWS_MicrocontrollerDrivers R24-11
 * PLATFORM    : NXP S32K144 (ARM Cortex-M4)
 ******************************************************************************/
 
#ifndef MCU_CFG_H
#define MCU_CFG_H
 
#include "../../../Common/Std_Type.h"

 
/*******************************************************************************
 * MODULE VERSION INFO
 *
 * WHY: AUTOSAR yêu cầu mỗi module có version để kiểm tra compatibility
 *      khi include nhau. Dùng trong Mcu_GetVersionInfo().
 ******************************************************************************/
#define MCU_VENDOR_ID           0x0050u   /* Vendor ID: ví dụ 0x0050 = NXP   */
#define MCU_MODULE_ID           0x0066u   /* Module ID 102 = Mcu (AUTOSAR)   */
#define MCU_SW_MAJOR_VERSION    1u
#define MCU_SW_MINOR_VERSION    0u
#define MCU_SW_PATCH_VERSION    0u
 
/*******************************************************************************
 * DEVELOPMENT ERROR DETECTION (DET)
 *
 * WHY: Trong development mode, Mcu sẽ gọi Det_ReportError() khi phát hiện
 *      lỗi sử dụng API sai (NULL pointer, sai thứ tự gọi...).
 *      Trong production (release build), tắt đi để tiết kiệm ROM/thời gian.
 *
 *      STD_ON  = bật DET → dùng khi debug
 *      STD_OFF = tắt DET → dùng khi release
 ******************************************************************************/
#define MCU_DEV_ERROR_DETECT    STD_ON
 
/*******************************************************************************
 * OPTIONAL API SWITCHES
 *
 * WHY: Một số API không bắt buộc theo AUTOSAR SWS.
 *      Nếu project không cần, tắt đi để tiết kiệm ROM.
 ******************************************************************************/
 
/* Bật/tắt API Mcu_GetVersionInfo() */
#define MCU_VERSION_INFO_API    STD_ON
 
/* Bật/tắt API Mcu_PerformReset() */
#define MCU_PERFORM_RESET_API   STD_ON
 
/* Bật/tắt API Mcu_GetRamState() — kiểm tra RAM integrity */
#define MCU_GET_RAM_STATE_API   STD_OFF   /* S32K144 không có ECC RAM check */
 
/*******************************************************************************
 * CLOCK CONFIGURATION
 *
 * S32K144 target: SOSC 8MHz → SPLL → 112MHz System Clock
 *   Core  = 112MHz / 1 = 112MHz
 *   Bus   = 112MHz / 2 = 56MHz
 *   Flash = 112MHz / 4 = 28MHz  (Flash max = 26.67MHz → thực tế dùng /5)
 ******************************************************************************/
 
/* Số lượng clock settings được define trong Mcu_Cfg.c */
#define MCU_MAX_CLOCK_SETTINGS  2u
 
/* Index của từng clock setting — dùng khi gọi Mcu_InitClock() */
#define MCU_CLOCKSETTING_NORMALRUN    0u   /* 112MHz full speed              */
#define MCU_CLOCKSETTING_LOWPOWER     1u   /* 8MHz FIRC, tiết kiệm điện      */
 
/*******************************************************************************
 * MODE CONFIGURATION
 *
 * Mcu_ModeType là typedef uint8 — chỉ là ID số nguyên.
 * Các define bên dưới là ID để truyền vào Mcu_SetMode().
 * Mapping ID → hardware mode được định nghĩa trong Mcu_ModeConfigType table.
 ******************************************************************************/
 
/* Số lượng power mode configs */
#define MCU_MAX_MODE_CONFIGS        3u
 
/* Mode IDs — truyền trực tiếp vào Mcu_SetMode(McuModeId) */
#define MCU_MODE_ID_RUN             ((Mcu_ModeType)0u)  /* Normal 112MHz      */
#define MCU_MODE_ID_STOP            ((Mcu_ModeType)1u)  /* CPU stop, periph on*/
#define MCU_MODE_ID_VLPS            ((Mcu_ModeType)2u)  /* Very low power stop*/
 
/*******************************************************************************
 * RAM SECTION CONFIGURATION
 ******************************************************************************/
 
/* Số lượng RAM sections cần init */
#define MCU_MAX_RAM_SECTIONS        1u
 
/* RAM Section IDs — truyền vào Mcu_InitRamSection() */
#define MCU_RAMSECTION_ID_MAIN      ((Mcu_RamSectionType)0u)
 
/*******************************************************************************
 * S32K144 PERIPHERAL CLOCK ENABLES
 *
 * WHY: Khi init clock, Mcu driver cần enable clock cho các peripheral
 *      được dùng trong project. Dùng STD_ON/STD_OFF để chọn.
 *      Map trực tiếp sang PCC register enable trong Mcu.c.
 ******************************************************************************/
#define MCU_PCC_PORTA_ENABLE    STD_ON
#define MCU_PCC_PORTB_ENABLE    STD_ON
#define MCU_PCC_PORTC_ENABLE    STD_ON
#define MCU_PCC_PORTD_ENABLE    STD_ON
#define MCU_PCC_PORTE_ENABLE    STD_ON

#define MCU_PCC_FLEXCAN0_ENABLE STD_ON
#define MCU_PCC_ADC0_ENABLE     STD_ON
#define MCU_PCC_LPSPI0_ENABLE   STD_OFF
#define MCU_PCC_LPUART0_ENABLE  STD_OFF
#define MCU_PCC_FTM0_ENABLE     STD_ON    /* FlexTimer cho PWM              */
#define MCU_PCC_LPIT0_ENABLE    STD_ON    /* Low Power Interrupt Timer      */
 
/*******************************************************************************
 * DET ERROR IDs
 *
 * WHY: Khi Mcu phát hiện lỗi, nó báo cho DET (Development Error Tracer)
 *      với API ID và Error ID cụ thể. Giúp debug biết lỗi xảy ra ở đâu.
 ******************************************************************************/
#define MCU_E_PARAM_CONFIG          0x0Au  /* NULL config pointer            */
#define MCU_E_PARAM_CLOCK           0x0Bu  /* Clock setting index out of range*/
#define MCU_E_PARAM_MODE            0x0Cu  /* Mode index out of range        */
#define MCU_E_UNINIT                0x0Du  /* API called before Mcu_Init()   */
#define MCU_E_PLL_NOT_LOCKED        0x0Eu  /* DistributePll called, not locked*/
 
/* API Service IDs — dùng trong Det_ReportError() */
#define MCU_SID_INIT                0x00u
#define MCU_SID_INIT_CLOCK          0x01u
#define MCU_SID_DISTRIBUTE_PLL      0x02u
#define MCU_SID_GET_PLL_STATUS      0x03u
#define MCU_SID_GET_RESET_REASON    0x04u
#define MCU_SID_GET_RESET_RAW       0x05u
#define MCU_SID_SET_MODE            0x06u
#define MCU_SID_PERFORM_RESET       0x07u
#define MCU_SID_GET_VERSION_INFO    0x08u
 
#endif /* MCU_CFG_H */
 
/*******************************************************************************
 * END OF FILE: Mcu_Cfg.h
 ******************************************************************************/
